pipeline:
  setup:
    image: gcc:latest
    commands:
      - mkdir -p build

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - build
    volumes:
      - /tmp/cache:/cache

  build:
    image: gcc:latest
    commands:
      - cd build
      - apt-get update
      - apt-get -y install cmake lcov
      - cmake -DBUILD_TESTS=ON -DBUILD_DEBUG=OFF ..
      - make
      - cd ..

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - build
    volumes:
      - /tmp/cache:/cache
